### ISSUE TITLE
Struggling to get it working!

### ISSUE THREAD

**Issue by kdthomas2121** [castwide/atom-solargraph#3]
I've verified it's running in the console, received "Solargraph package activated." 
It then prints that a lot of required paths aren't found.

However, I'm struggling to get it to autocomplete, I've tried running the example in the readme to get capitalise to show, but when I write "string." nothing appears, even after pressing control space

Any help would be appreciated!

**Comment by castwide** [comment]
Try updating the gem first. Today I published version 0.17.1. It resolves an issue with infinite recursion loops in some workspace environments.

Since you're getting messages about required paths in the console, I assume you're using it on an existing project. Sometimes it can take a while to process the maps on very large projects. Rails apps are especially susceptible to this. After the initial mapping, requests should become much faster.

Make sure you're capitalizing `String` to get class method suggestions. Results are case-sensitive.

If you still have problems, please let me know your OS, the versions of the Solargraph gem and the Atom package, and any errors you see in the console.

**Comment by castwide** [comment]
Version 0.2.0 of the package fixes an issue with project directories that might resolve your problem. There's also a new version of the gem, so be sure to `gem update solargraph`.

**Comment by FunkyloverOne** [comment]
@castwide how to verify it's running? I'm running this in terminal - `solargraph socket`, and receive 
`Solargraph is listening PORT=7658 PID=13393`
Then I run atom, also from terminal, ruby versions are same, package installed & enabled, but I can't see it's working.

**Comment by castwide** [comment]
It occurred to me that you might be able to get it to work with an earlier version of the gem, so I tested a few of them and was able to get results with v0.17.4.

Installing the gem:
```
gem uninstall solargraph
gem install solargraph -v 0.17.4
```

Results in Atom:

![image](https://user-images.githubusercontent.com/3704922/39308724-275a0cce-4934-11e8-9496-53bd73b74b79.png)

You still might encounter issues that have been resolved in the latest gem. I'll update #5 when the package is able to use it.

**Comment by michielboekhoff** [comment]
@castwide this tool is awesome! Got it working today using the master branch. For anyone else struggling to get this running, I ran `apm install https://github.com/castwide/atom-solargraph.git` from the command line and it works with the latest version of the gem.

**Comment by castwide** [comment]
Version 0.3.0 with LSP support is published.

**Comment by FunkyloverOne** [comment]
@castwide For me version 0.3.0 still doesn't seem to work at all... I got my ruby installed via `ruby-install`+`chruby`, and stuff like `linter-rubocop` and `linter-reek` is working.

**Comment by castwide** [comment]
@FunkyloverOne That should work, yes. I'll work on an update to atom-solargraph. I'm also in the process of an update to solargraph-utils that should help fix some other issues related to starting the server process.

**Comment by svoop** [comment]
@castwide Any news on this? It'd be very cool to use solargraph together with chruby.

**Comment by castwide** [comment]
@svoop The `master` branch now includes two important updates:
* It uses the latest version of `solargraph-utils`, which improves automatic environment detection.
* It adds a `commandPath` configuration option.

I expect to publish the package in the next few days.

**Comment by FunkyloverOne** [comment]
@castwide I can confirm that I've finally succeeded! :D

I had to start Atom from terminal though.
Currently `linter-rubocop` and `linter-reek` are working somehow even without having to start Atom from terminal, I have no idea how they are doing it.

Yet what we have now is a good start indeed! Thank you!

**Comment by FunkyloverOne** [comment]
Hey @castwide, here's what does the trick for reek and rubocop I believe:
https://github.com/steelbrain/atom-linter/issues/62

**Comment by castwide** [comment]
Thanks, @FunkyloverOne. That looks promising. Since the current version of atom-solargraph seems like a step in the right direction for most users, I'll still release it this week, but I'll refer to that thread for possible improvements.

**Comment by castwide** [comment]
Version 0.4.0 is released with the commandPath configuration option.
